window.BUSHWAR_COMPOSER_RELEASE = {
  version: "0.10.2",
  published: "12 August 2026",
  title: "Reliable Workbench pixel handoff",
  summary: "Workbench exports now use the same Position/Size slots as the shipped BUSHWAR GM layouts, so imported panels no longer collapse into the top-left corner.",
  changes: [
    "Connected players uses PlayerManager.GetPlayers(out playerIds) + GetPlayerName(playerId), with empty-name filtering and no guessed ID range.",
    "The inspector now separates Engine data / function bindings from Engine callback / action contracts.",
    "Connected-player tables default to a row-selection contract that carries the real playerId into the controller.",
    "The GM base template no longer seeds fake Alpha/Bravo/Charlie player rows; it uses the engine-backed table instead.",
    "Workbench plans now export callbacks alongside runtimeScaffolds with named count/scroll/list widgets and native Button/Text row scaffolds.",
    "Table previews show a truthful runtime-backed design row instead of fake player placeholders.",
    "Native Workbench scaffold output uses supported layout properties and pixel-fixed slots so a 24 px / 360 px panel stays the same at the exported root size.",
    "Connected-player row scaffolds use native Button/Text widgets with vertical padding, and the runtime controller applies the Composer font contract with TextWidget.SetExactFontSize().",
    "Handoff validation now flags static player-name text without a runtime binding instead of allowing fake Alpha/Bravo/Sgt.James rows through silently.",
    "Schema 3 Workbench plans include controllerPath and controllerSource, plus a one-click EnforceScript controller export.",
    "Connected-player scaffolds include a named selection label; generated OnPlayerRowClicked writes SELECTED: <engine name> while retaining the real playerId.",
    "Generated controllers include a throttled OnUpdate signature check so joins, leaves, and name changes refresh the native rows without rebuilding every frame.",
    "The widget profile database maps palette elements to native Frame, Text, Button, Image, ProgressBar, EditBox, CheckBox, and layout-container classes.",
    "Reforger catalogue cards now show their native widget-class hint and the Workbench action required to use the source-backed prefab or atlas.",
    "Schema 3 plans carry nativeProfileSchema/nativeWidgetClasses, and the disposable Workbench review plug-in rejects handoffs that omit the mapping.",
    "Import Workbench context JSON to preview the real connected-player roster; without it, the browser shows an explicit runtime placeholder instead of fake rows.",
    "Generated plans now carry engine-context provenance, runtime authority, refresh events, row identity, and callback implementation status.",
    "Player-row callback scaffolds retain the actual PlayerManager ID and emit a compile-safe review hook for server-authoritative actions such as teleport.",
    "Export complete Workbench handoff packages the design bundle, schema-3 plan, controller source, and context contract into one transferable JSON file.",
    "The validation addon compiles the exported controller pattern and uses local InputManager variables, matching the engine's private-destructor contract.",
    "Generated FrameWidgetSlot geometry now uses PositionX/PositionY/SizeX/SizeY with point anchors, matching the shipped BUSHWAR GM menu and preventing the cramped top-left import seen with older handoff files.",
    "The disposable admin-menu fixtures use the same Position/Size bounds: left 24 px, top 15%, width 360 px, bottom 80%."
  ]
};
