window.BUSHWAR_COMPOSER_RELEASE = {
  version: "0.10.57",
  published: "13 August 2026",
  title: "Roomier sidebar, collapsible panels, mod-prep hints",
  summary: "The right sidebar is wider and its sections collapse for vertical room; the workflow tracker folds into a live summary, and a Mod prep note shows the controller path and Core dependency before you export.",
  changes: [
    "Right sidebar widened from 270px to 320px so Handoff fields and export actions fit comfortably.",
    "Right-sidebar sections (Selection, Screen, Handoff, Engine context) are now collapsible, so you can extend the panel vertically and focus on one area.",
    "The Workbench workflow tracker collapses into a summary line with a live ready count; open it to see the eight steps.",
    "A live Mod prep note shows the generated controller target (Scripts/Game/UI/…) and whether the BUSHWAR-UIComposer-Core dependency (B3A5F08C0D504D96) is required, updated as you design.",
    "The Workbench workflow guide now includes a Mod prep checklist (dependency, controller path, layout registration, textures, authority boundary).",
    "The ui-audit regression test now locks the sidebar sizing, collapsible sections, and mod-prep note.",
    "Removed the duplicate topbar Scene picker (the Base scene cards are now the single picker) and the redundant Copy design specification action; the schema-3 plan and handoff bundle already carry the same information.",
    "Handoff actions are grouped into compact rows: Export handoff bundle + Export controller, and Copy scaffold + Download scaffold, with shorter labels.",
    "Design refresh: rounded buttons, hover states on primary actions, visible :focus-visible rings for keyboard navigation, and prefers-reduced-motion support.",
    "Accessibility: the status bar announces changes to screen readers (aria-live), icon-only layer buttons carry aria-labels, and toggle buttons expose aria-pressed state.",
    "A new ui-audit regression test locks the cleanup in place: every button must be wired or a delegated/dialog action, and no orphaned or dead controls may return.",
    "A Workbench workflow tracker in the Handoff panel shows the eight-step WR pipeline with live status; the four automatic steps turn green as your design and Handoff fields are ready, and the four Workbench-side steps stay marked manual.",
    "Exported schema-3 plans now embed a handoff readiness block (ready, issues, layoutGuidSet, controllerGuidQualified, and GUID-qualified row resources) so the Workbench import-plan plugin can reject not-ready handoffs programmatically.",
    "New Download layout scaffold request button saves the layoutCreateRequest JSON as a file next to the existing clipboard copy.",
    "New Workbench workflow guide dialog documents the full Composer → Workbench pipeline and the fidelity contract: native widgets only, registered textures, Workbench-owned .layout XML, GUID-qualified ResourceNames, and PlayerManager-authoritative bindings.",
    "The dedicated Reforger runtime mod (BUSHWAR-UIComposer-Core) now owns the registered player-row layout plus generic runtime scripts (layout controller base and a safe PlayerManager list helper); the GM admin panel is deliberately not part of it and stays with the GM tools side.",
    "The website Core library manifest exposes only the registered player-row resource; saved projects containing legacy admin-panel layers still import through the preserved app.js path.",
    "The validation addon's admin menu now uses its own registered admin-menu layout ({1D2CEED7BB782E8D}) instead of the Core admin panel.",
    "Runtime verification on Reforger 1.8: both addons compile clean in Workbench, both layouts resolve with their registered GUIDs, and the Arland test world loads in game mode (189,762 entities).",
    "Generic Connected players (engine) tables now use the registered BUSHWAR Core Button Row > NameText prefab by default, so PlayerManager rows can actually instantiate in Reforger instead of silently failing on a bare path.",
    "Schema-3 handoffs now list runtime row resources and the required BUSHWAR-UIComposer-Core dependency; validation warns when a custom row layout is not GUID-qualified.",
    "Registered .layout.meta imports now preserve the full normalized resource path instead of reconstructing only the filename; changing the layout name clears the imported path so stale metadata cannot leak into a new handoff.",
    "Connected players uses PlayerManager.GetPlayers(playerIds) + GetPlayerName(playerId) (the API marks the array out, but EnforceScript call syntax omits the keyword), with empty-name filtering and no guessed ID range.",
    "The inspector now separates Engine data / function bindings from Engine callback / action contracts.",
    "Connected-player tables default to a row-selection contract that carries the real playerId into the controller.",
    "The GM base template no longer seeds fake Alpha/Bravo/Charlie player rows; it uses the engine-backed table instead.",
    "Workbench plans now export callbacks alongside runtimeScaffolds with named count/scroll/list widgets and native Button/Text row scaffolds.",
    "Table previews show a truthful runtime-backed design row instead of fake player placeholders.",
    "Native Workbench scaffold output uses supported layout properties and pixel-fixed slots so a 24 px / 360 px panel stays the same at the exported root size.",
    "Connected-player row scaffolds use native Button/Text widgets with vertical padding, and the runtime controller applies the Composer font contract with TextWidget.SetExactFontSize().",
    "Handoff validation now flags static player-name text without a runtime binding instead of allowing fake Alpha/Bravo/Sgt.James rows through silently.",
    "Schema 3 Workbench plans include controllerPath and controllerSource, plus a one-click EnforceScript controller export.",
    "Connected-player scaffolds include a named selection label; generated OnPlayerRowClicked writes SELECTED: <engine name> while retaining the real playerId.",
    "Generated controllers include a throttled OnUpdate signature check so joins, leaves, and name changes refresh the native rows without rebuilding every frame.",
    "The widget profile database maps palette elements to native Frame, Text, Button, Image, ProgressBar, EditBox, CheckBox, and layout-container classes.",
    "Reforger catalogue cards now show their native widget-class hint and the Workbench action required to use the source-backed prefab or atlas.",
    "Schema 3 plans carry nativeProfileSchema/nativeWidgetClasses, and the disposable Workbench review plug-in rejects handoffs that omit the mapping.",
    "Import Workbench context JSON to preview the real connected-player roster; without it, the browser shows an explicit runtime placeholder instead of fake rows.",
    "Generated plans now carry engine-context provenance, runtime authority, refresh events, row identity, and callback implementation status.",
    "Player-row callback scaffolds retain the actual PlayerManager ID and emit a compile-safe review hook for server-authoritative actions such as teleport.",
    "Export complete Workbench handoff packages the design bundle, schema-3 plan, controller source, and context contract into one transferable JSON file.",
    "The validation addon compiles the exported controller pattern and uses local InputManager variables, matching the engine's private-destructor contract.",
    "Generated FrameWidgetSlot geometry now uses the current Reforger PositionX/PositionY/SizeX/SizeY fixed-pixel form, preventing the cramped top-left import caused by legacy Offset* bounds.",
    "The Core admin panel and disposable handoff fixtures use the same native geometry: left 24 px, top 15%, width 360 px, bottom 80%.",
    "Browser and PNG previews for Connected players now mirror the native count / selection / scroll / Button row / NameText scaffold; empty context shows zero rows rather than invented player entries.",
    "Imported engine context is normalized to positive, unique player IDs with non-empty names, and clicking a preview row records the real PlayerManager ID used by the generated callback contract.",
    "Generated native widget names are deterministic and duplicate-safe across the layout scaffold, plan, and controller source; callback routes now expose explicit review hooks instead of silently pretending an action is implemented.",
    "Generated PlayerManager calls now use the compile-valid GetPlayers(playerIds) call syntax for the API's out array parameter.",
    "Text and badge widgets can bind to Player display name or GM editor state; the preview shows the imported value or an explicit unknown-state placeholder.",
    "Binding selectors are filtered to compatible widget types and handoff validation warns before a binding is attached to an incompatible layer.",
    "The disposable Workbench controller fixture was recompiled after the GetPlayers signature correction; its fresh Game module log contains no BWUIC script errors.",
    "Connected player count is now a real PlayerManager-backed scalar binding for text and badge widgets; without an imported snapshot the browser shows an explicit unknown value.",
    "The new Refresh live engine values callback re-queries connected rows and scalar bindings in memory when a designed refresh button is clicked; it does not export player data to disk.",
    "npm test now validates generated connected-player, player-count, and live-refresh source contracts and rejects accidental GetPlayers(out ...) emission before publishing.",
    "Validate Workbench handoff now inspects the generated controller source and warns if connected-player, player-count, or live-refresh routes are missing.",
    "Player display-name bindings on Player-row Buttons now target the generated Text child instead of casting the Button root as a TextWidget.",
    "Generated callback routes walk the clicked widget's parent chain, so WLib buttons and nested source-backed controls reach the assigned Composer callback contract.",
    "Validate Workbench handoff now includes a per-layer runtime contract audit with native target widget, engine source, callback, authority, and READY/REVIEW/ERROR status.",
    "Hidden runtime-bound layers are warned because hidden layers are intentionally omitted from the exported Workbench layout.",
    "Preview mode now exercises safe callback contracts locally (refresh, open/close, and click) and labels review-required actions without claiming to mutate game state.",
    "The GM admin template now includes a PlayerManager-backed connected-count badge and a Refresh live values button wired to the generated engine.context.refresh route.",
    "Generated controllers now apply each layer's Composer font size with TextWidget.SetExactFontSize when the native layout opens, reducing the visual gap between the website and Workbench.",
    "Connected-player controllers keep exactly one native row per valid PlayerManager ID; nested WLib/Text children resolve through the row's parent chain instead of becoming duplicate rows.",
    "Runtime bindings now declare their live source of truth, empty-value policy, identity field, and snapshot-only browser preview policy in the handoff contract.",
    "Palette layers can adopt their recommended registered WLib layout source from the inspector; source/sourceBacked metadata travels with the Workbench plan while existing engine bindings and callbacks stay attached.",
    "Source-backed runtime lists are flagged for named-child verification in Workbench instead of silently pretending a prefab's internal hierarchy matches the Composer scaffold.",
    "The connected-player binding is table-only; standalone Player rows must use the Player display-name binding so generated controllers cannot target a missing list scaffold.",
    "Schema-3 plans summarize source-backed widget counts and required named-child verification for the disposable Workbench review plugin.",
    "New palette and template layers adopt a registered vanilla/WLib source by default when one exists; use the inspector's generated-native action when a custom scaffold is intentional.",
    "Connected-player tables remain native runtime scaffolds until their Count/Selection/Scroll/List/NameText child names are verified against the selected Reforger source.",
    "Any source-backed runtime binding now carries a manual child-name verification gate, and scalar bindings can override the exact runtime TextWidget child name in the inspector.",
    "The schema-3 runtime scaffold preserves layer type, widget properties, and runtime contracts before controller generation; verified child overrides are no longer dropped from the generated EnforceScript.",
    "Pixel-authored layout slots now export PositionX/PositionY/SizeX/SizeY rectangles, matching Workbench's current anchored FrameWidgetSlot form and preserving the requested 24 px / 360 px GM panel bounds.",
    "Native Reforger recipes add proven info-panel, status, progress, timer, icon-overlay, and GM connected-player trees with named child contracts; applying one creates editable layers plus the callback metadata used by the Workbench handoff.",
    "The GM editor binding now emits SCR_EditorManagerEntity.IsOpenedInstance(true), matching the engine contract's includeLimited parameter.",
    "Toggle widget visibility is a generated client-local action: choose an exact Workbench widget name or leave the target blank to toggle the clicked widget, with the same behavior represented in browser preview.",
    "Connected-player refresh now resets the count and selection labels when PlayerManager is unavailable, and row selection rejects stale IDs or empty names instead of showing an invalid player.",
    "Set text on widget is a generated client-local action: choose an exact TextWidget name and the controller emits TextWidget.SetText with the designed value; browser preview updates the same target layer.",
    "Pixel-authored Workbench layout slots no longer rely on legacy OffsetRight/OffsetBottom values; fixed Position/Size fields keep the rectangle out of the top-left collapse path.",
    "Engine context export generates a JsonApiStruct snapshot at $profile:BUSHWAR-UIComposer/runtime-context.json, filtering empty PlayerManager names before writing; import that file in the website to preview real engine evidence.",
    "Callback-only controls are now retained in schema-3 runtimeScaffolds, so actions such as visibility, text, refresh, and context export cannot disappear simply because the layer has no data binding.",
    "The function catalogue no longer publishes duplicate Set text entries.",
    "WCA now boots to a blank 1920 × 1080 workspace instead of automatically loading the GM template.",
    "A landing dialog makes restoring the previous meaningful session explicit, so saved work is preserved without making the default canvas non-blank.",
    "The landing page offers direct access to the template library while keeping base scenes and templates as deliberate choices.",
    "The companion BUSHWAR-UIComposer-Core addon now has a matching website manifest for the admin panel and connected-player row layout resources.",
    "Core catalog layers preserve their addon identity, required named children, and runtime contract declarations in the Workbench handoff instead of treating them as generic visual references.",
    "The Reforger database filter separates BUSHWAR Core resources from vanilla path references; Core layouts still require fresh Workbench registration and metadata generation.",
    "Selecting a Core admin panel or player row now attaches its real layout path, Core addon identity, named children, row layout, binding, and callback metadata to the Workbench handoff.",
    "The Core admin panel preview mirrors its native title, refresh control, count, selection label, and zero-or-real-player list instead of using the generic reference-card mock.",
    "The disposable validation controller now consumes the registered Core layout GUIDs and declares the Core addon dependency, exercising the same resource path the website exports.",
    "Reforger catalog cards now list callback hints such as OnClick, OnUpdate, SetText, layout open/close, and connected-player selection; these hints travel with the selected layer into the schema-3 Workbench plan.",
    "The BUSHWAR Core manifest is version 0.1.2 and records the same callback hints plus the corrected native fixed-pixel geometry for its registered admin panel and player-row resources.",
    "Core admin panels now expose canonical count/selection/scroll/list/row child keys while retaining legacy aliases, so imported older projects still generate valid FindAnyWidget targets instead of undefined names.",
    "Connected-player layoutCreateRequest scaffolds and generated font routes now use the resolved named-child contract (including Core m_wPlayerCount/m_wPlayerList) and preserve the registered source-backed layout reference.",
    "Controller generation now accepts both requiredWidgetNames and requiredNamedChildren contracts; regression coverage proves Core m_wPlayerList and m_wPlayerSelection reach the final EnforceScript source.",
    "Core connected-player panels now carry {F487371808027463}UI/layouts/BWUIC_CorePlayerRow.layout into the generated ResourceName, avoiding ambiguous bare-path row creation.",
    "Validate Workbench handoff now treats the registered BUSHWAR Core child tree as manifest-verified while preserving manual child-name warnings for unverified vanilla/source-backed runtime layouts.",
    "Opening or restoring an older project/template now hydrates matching Core layers from the current manifest, including the GUID-qualified player-row ResourceName and runtime callback contracts.",
    "The Composer test suite now constructs a Core admin layer and verifies its exported widget, native count/selection/scroll/list children, GUID-qualified source, and registered row layout agree as one contract.",
    "Core library tests now compare each manifest ResourceName with the actual .layout.meta file and validation controller, catching null or stale GUID registration before a Workbench handoff is used.",
    "Generated controllers and the disposable validation admin menu now deduplicate PlayerManager IDs before creating rows or calculating connected counts, while still skipping empty names.",
    "Exported runtime-context snapshots and roster signatures use the same unique-ID rule, so browser previews cannot gain duplicate or placeholder player entries from a malformed engine list.",
    "The browser context normalizer now has an executable regression fixture covering duplicate IDs, empty names, non-positive IDs, invalid IDs, and multiple valid players before a snapshot reaches the canvas.",
    "Imported zero-player snapshots now render 0 connected and an explicit Workbench-empty message; no snapshot remains an unknown state instead of pretending the engine reported zero.",
    "Generated controllers and validation fixtures reject non-positive PlayerManager IDs before name lookup, row creation, scalar counts, signatures, or context export.",
    "Connected-player canvas and PNG previews now show ENGINE SNAPSHOT REQUIRED when no Workbench context exists, and WORKBENCH REPORTS 0 PLAYERS when an imported snapshot is genuinely empty.",
    "Workbench plans and runtime contracts now carry snapshotLoaded and playerCountKnown flags, so downstream import tooling can distinguish unknown engine state from a verified empty roster.",
    "Generated connected-player child slots now use Position/Size rectangles, matching the fixed-pixel root geometry and preventing fractional-anchor drift in Workbench.",
    "Core admin-panel handoffs now include the native title, refresh/close controls, count, selection, scroll, and list child tree; validation warns if the registered 24 px / 360 px / 15%-80% Core geometry is changed.",
    "Core catalog entries now use the native 360 px admin panel, 15%-80% vertical slot, and compact 332 px player-row geometry instead of the generic reference-card fallback.",
    "Connected-player runtime controllers now reject row prefabs missing the required NameText child, start native rows without a placeholder name, and report PLAYER DATA UNAVAILABLE when PlayerManager cannot be read instead of claiming zero players.",
    "The validation admin menu now routes nested row clicks through their canonical row, exposes the native refresh button, and clears/imports zero-player context without confusing it with an unavailable engine snapshot.",
    "Handoff settings now accept the target layout's registered 16-character Workbench GUID; the generated controller and plan use the qualified ResourceName, while validation warns before compiling a bare relative path.",
    "The disposable Workbench import-plan plugin now rejects schema-3 plans missing layoutResourceReference, preventing a visually correct browser design from being treated as a compiled runtime handoff without a registered layout.",
    "Handoff can now load a local .layout.meta file, extract its non-null GUID and resource path, and populate the layout name/GUID fields without uploading the metadata.",
    "Widget update callbacks now attach the generated controller to the exact target widget, throttle OnUpdate to 30 ticks, refresh linked engine-backed values when available, and expose a compile-safe target-addon seam without misrouting the callback through OnClick.",
    "Handoff validation and controller-source tests now fail when a Widget update assignment loses its target-widget route.",
    "Player count bindings now emit PlayerManager.GetPlayerCount() in the native controller; the connected table still uses GetPlayers(playerIds) and GetPlayerName(playerId) to create only valid named rows.",
    "Runtime context snapshots now carry playerCount/playerCountKnown from PlayerManager.GetPlayerCount(); browser previews display that authoritative scalar separately from filtered validNamedPlayerRows and show unknown when the engine cannot provide it.",
    "Generated connected-player table headers now use the same PlayerManager.GetPlayerCount() scalar as standalone count bindings; invalid or unnamed IDs still never create visual rows."
  ]
};
