window.BUSHWAR_COMPOSER_RELEASE = {
  version: "0.10.29",
  published: "13 August 2026",
  title: "Native connected-player scaffold parity",
  summary: "WCA now uses the selected Core or source-backed connected-player child names in both the generated layout scaffold and controller, keeping the exported native tree aligned with the actual Reforger layout.",
  changes: [
    "Connected players uses PlayerManager.GetPlayers(playerIds) + GetPlayerName(playerId) (the API marks the array out, but EnforceScript call syntax omits the keyword), with empty-name filtering and no guessed ID range.",
    "The inspector now separates Engine data / function bindings from Engine callback / action contracts.",
    "Connected-player tables default to a row-selection contract that carries the real playerId into the controller.",
    "The GM base template no longer seeds fake Alpha/Bravo/Charlie player rows; it uses the engine-backed table instead.",
    "Workbench plans now export callbacks alongside runtimeScaffolds with named count/scroll/list widgets and native Button/Text row scaffolds.",
    "Table previews show a truthful runtime-backed design row instead of fake player placeholders.",
    "Native Workbench scaffold output uses supported layout properties and pixel-fixed slots so a 24 px / 360 px panel stays the same at the exported root size.",
    "Connected-player row scaffolds use native Button/Text widgets with vertical padding, and the runtime controller applies the Composer font contract with TextWidget.SetExactFontSize().",
    "Handoff validation now flags static player-name text without a runtime binding instead of allowing fake Alpha/Bravo/Sgt.James rows through silently.",
    "Schema 3 Workbench plans include controllerPath and controllerSource, plus a one-click EnforceScript controller export.",
    "Connected-player scaffolds include a named selection label; generated OnPlayerRowClicked writes SELECTED: <engine name> while retaining the real playerId.",
    "Generated controllers include a throttled OnUpdate signature check so joins, leaves, and name changes refresh the native rows without rebuilding every frame.",
    "The widget profile database maps palette elements to native Frame, Text, Button, Image, ProgressBar, EditBox, CheckBox, and layout-container classes.",
    "Reforger catalogue cards now show their native widget-class hint and the Workbench action required to use the source-backed prefab or atlas.",
    "Schema 3 plans carry nativeProfileSchema/nativeWidgetClasses, and the disposable Workbench review plug-in rejects handoffs that omit the mapping.",
    "Import Workbench context JSON to preview the real connected-player roster; without it, the browser shows an explicit runtime placeholder instead of fake rows.",
    "Generated plans now carry engine-context provenance, runtime authority, refresh events, row identity, and callback implementation status.",
    "Player-row callback scaffolds retain the actual PlayerManager ID and emit a compile-safe review hook for server-authoritative actions such as teleport.",
    "Export complete Workbench handoff packages the design bundle, schema-3 plan, controller source, and context contract into one transferable JSON file.",
    "The validation addon compiles the exported controller pattern and uses local InputManager variables, matching the engine's private-destructor contract.",
    "Generated FrameWidgetSlot geometry uses point anchors with signed OffsetRight/OffsetBottom edges, matching the shipped BUSHWAR GM menu and preventing the cramped top-left import seen with older handoff files.",
    "The disposable admin-menu fixtures use the same Offset* bounds: left 24 px, top 15%, width 360 px, bottom 80%.",
    "Browser and PNG previews for Connected players now mirror the native count / selection / scroll / Button row / NameText scaffold; empty context shows zero rows rather than invented player entries.",
    "Imported engine context is normalized to positive, unique player IDs with non-empty names, and clicking a preview row records the real PlayerManager ID used by the generated callback contract.",
    "Generated native widget names are deterministic and duplicate-safe across the layout scaffold, plan, and controller source; callback routes now expose explicit review hooks instead of silently pretending an action is implemented.",
    "Generated PlayerManager calls now use the compile-valid GetPlayers(playerIds) call syntax for the API's out array parameter.",
    "Text and badge widgets can bind to Player display name or GM editor state; the preview shows the imported value or an explicit unknown-state placeholder.",
    "Binding selectors are filtered to compatible widget types and handoff validation warns before a binding is attached to an incompatible layer.",
    "The disposable Workbench controller fixture was recompiled after the GetPlayers signature correction; its fresh Game module log contains no BWUIC script errors.",
    "Connected player count is now a real PlayerManager-backed scalar binding for text and badge widgets; without an imported snapshot the browser shows an explicit unknown value.",
    "The new Refresh live engine values callback re-queries connected rows and scalar bindings in memory when a designed refresh button is clicked; it does not export player data to disk.",
    "npm test now validates generated connected-player, player-count, and live-refresh source contracts and rejects accidental GetPlayers(out ...) emission before publishing.",
    "Validate Workbench handoff now inspects the generated controller source and warns if connected-player, player-count, or live-refresh routes are missing.",
    "Player display-name bindings on Player-row Buttons now target the generated Text child instead of casting the Button root as a TextWidget.",
    "Generated callback routes walk the clicked widget's parent chain, so WLib buttons and nested source-backed controls reach the assigned Composer callback contract.",
    "Validate Workbench handoff now includes a per-layer runtime contract audit with native target widget, engine source, callback, authority, and READY/REVIEW/ERROR status.",
    "Hidden runtime-bound layers are warned because hidden layers are intentionally omitted from the exported Workbench layout.",
    "Preview mode now exercises safe callback contracts locally (refresh, open/close, and click) and labels review-required actions without claiming to mutate game state.",
    "The GM admin template now includes a PlayerManager-backed connected-count badge and a Refresh live values button wired to the generated engine.context.refresh route.",
    "Generated controllers now apply each layer's Composer font size with TextWidget.SetExactFontSize when the native layout opens, reducing the visual gap between the website and Workbench.",
    "Connected-player controllers keep exactly one native row per valid PlayerManager ID; nested WLib/Text children resolve through the row's parent chain instead of becoming duplicate rows.",
    "Runtime bindings now declare their live source of truth, empty-value policy, identity field, and snapshot-only browser preview policy in the handoff contract.",
    "Palette layers can adopt their recommended registered WLib layout source from the inspector; source/sourceBacked metadata travels with the Workbench plan while existing engine bindings and callbacks stay attached.",
    "Source-backed runtime lists are flagged for named-child verification in Workbench instead of silently pretending a prefab's internal hierarchy matches the Composer scaffold.",
    "The connected-player binding is table-only; standalone Player rows must use the Player display-name binding so generated controllers cannot target a missing list scaffold.",
    "Schema-3 plans summarize source-backed widget counts and required named-child verification for the disposable Workbench review plugin.",
    "New palette and template layers adopt a registered vanilla/WLib source by default when one exists; use the inspector's generated-native action when a custom scaffold is intentional.",
    "Connected-player tables remain native runtime scaffolds until their Count/Selection/Scroll/List/NameText child names are verified against the selected Reforger source.",
    "Any source-backed runtime binding now carries a manual child-name verification gate, and scalar bindings can override the exact runtime TextWidget child name in the inspector.",
    "The schema-3 runtime scaffold preserves layer type, widget properties, and runtime contracts before controller generation; verified child overrides are no longer dropped from the generated EnforceScript.",
    "Pixel-authored layout slots now export OffsetLeft/Top/Right/Bottom rectangles, matching Workbench's anchored FrameWidgetSlot form and preserving the requested 24 px / 360 px GM panel bounds.",
    "Native Reforger recipes add proven info-panel, status, progress, timer, icon-overlay, and GM connected-player trees with named child contracts; applying one creates editable layers plus the callback metadata used by the Workbench handoff.",
    "The GM editor binding now emits SCR_EditorManagerEntity.IsOpenedInstance(true), matching the engine contract's includeLimited parameter.",
    "Toggle widget visibility is a generated client-local action: choose an exact Workbench widget name or leave the target blank to toggle the clicked widget, with the same behavior represented in browser preview.",
    "Connected-player refresh now resets the count and selection labels when PlayerManager is unavailable, and row selection rejects stale IDs or empty names instead of showing an invalid player.",
    "Set text on widget is a generated client-local action: choose an exact TextWidget name and the controller emits TextWidget.SetText with the designed value; browser preview updates the same target layer.",
    "Pixel-authored Workbench layout slots now negate OffsetRight/OffsetBottom for point anchors; positive right/bottom values collapse a rectangle past the top-left origin.",
    "Engine context export generates a JsonApiStruct snapshot at $profile:BUSHWAR-UIComposer/runtime-context.json, filtering empty PlayerManager names before writing; import that file in the website to preview real engine evidence.",
    "Callback-only controls are now retained in schema-3 runtimeScaffolds, so actions such as visibility, text, refresh, and context export cannot disappear simply because the layer has no data binding.",
    "The function catalogue no longer publishes duplicate Set text entries.",
    "WCA now boots to a blank 1920 × 1080 workspace instead of automatically loading the GM template.",
    "A landing dialog makes restoring the previous meaningful session explicit, so saved work is preserved without making the default canvas non-blank.",
    "The landing page offers direct access to the template library while keeping base scenes and templates as deliberate choices.",
    "The companion BUSHWAR-UIComposer-Core addon now has a matching website manifest for the admin panel and connected-player row layout resources.",
    "Core catalog layers preserve their addon identity, required named children, and runtime contract declarations in the Workbench handoff instead of treating them as generic visual references.",
    "The Reforger database filter separates BUSHWAR Core resources from vanilla path references; Core layouts still require fresh Workbench registration and metadata generation.",
    "Selecting a Core admin panel or player row now attaches its real layout path, Core addon identity, named children, row layout, binding, and callback metadata to the Workbench handoff.",
    "The Core admin panel preview mirrors its native title, refresh control, count, selection label, and zero-or-real-player list instead of using the generic reference-card mock.",
    "The disposable validation controller now consumes the registered Core layout GUIDs and declares the Core addon dependency, exercising the same resource path the website exports.",
    "Reforger catalog cards now list callback hints such as OnClick, OnUpdate, SetText, layout open/close, and connected-player selection; these hints travel with the selected layer into the schema-3 Workbench plan.",
    "The BUSHWAR Core manifest is version 0.1.1 and records the same callback hints for its registered admin panel and player-row resources.",
    "Core admin panels now expose canonical count/selection/scroll/list/row child keys while retaining legacy aliases, so imported older projects still generate valid FindAnyWidget targets instead of undefined names.",
    "Connected-player layoutCreateRequest scaffolds and generated font routes now use the resolved named-child contract (including Core m_wPlayerCount/m_wPlayerList) and preserve the registered source-backed layout reference."
  ]
};
